<?php

namespace Anorm\Test;

use Anorm\DataMapper;
use Anorm\Relationship\OneHasMany;
use Anorm\Relationship\Strategy\QueryStrategySelector;
use PHPUnit\Framework\TestCase;

class RelationshipBase_Test extends TestCase
{
    private $pdo;

    public static function setUpBeforeClass(): void
    {
        TestEnvironment::connect();
        $pdo = TestEnvironment::pdo();

        $pdo->exec('SET FOREIGN_KEY_CHECKS=0');

        $sql = file_get_contents(__DIR__ . '/../RelationshipTestSchema.sql');
        $lines = explode("\n", $sql);
        $cleanSql = '';
        foreach ($lines as $line) {
            $line = trim($line);
            if (!empty($line) && strpos($line, '#') !== 0) {
                $cleanSql .= $line . "\n";
            }
        }

        foreach (explode(';', $cleanSql) as $statement) {
            $statement = trim($statement);
            if (!empty($statement)) {
                try {
                    $pdo->exec($statement);
                } catch (\PDOException $e) {
                    // Ignore errors during schema setup (e.g., table already exists)
                }
            }
        }

        $pdo->exec('SET FOREIGN_KEY_CHECKS=1');
    }

    protected function setUp(): void
    {
        $this->pdo = TestEnvironment::pdo();
    }

    // -------------------------------------------------------------------------
    // Relationship base class: getOptions(), getOption(), getConstraintName()
    // -------------------------------------------------------------------------

    public function testGetOptionsReturnsOptionsArray()
    {
        $options = ['constraints' => ['on_delete' => 'CASCADE', 'on_update' => 'CASCADE']];
        $rel = new OneHasMany('Anorm\Test\PostModel', 'posts', 'user_id', 'id', $options);

        $result = $rel->getOptions();

        $this->assertIsArray($result);
        $this->assertArrayHasKey('constraints', $result);
    }

    public function testGetOptionsReturnsEmptyArrayWhenNoOptions()
    {
        $rel = new OneHasMany('Anorm\Test\PostModel', 'posts', 'user_id', 'id');

        $result = $rel->getOptions();

        $this->assertIsArray($result);
        $this->assertEmpty($result);
    }

    public function testGetOptionReturnsValueForExistingKey()
    {
        $options = ['constraints' => ['on_delete' => 'CASCADE'], 'custom_key' => 'custom_value'];
        $rel = new OneHasMany('Anorm\Test\PostModel', 'posts', 'user_id', 'id', $options);

        $value = $rel->getOption('custom_key');

        $this->assertEquals('custom_value', $value);
    }

    public function testGetOptionReturnsDefaultForMissingKey()
    {
        $rel = new OneHasMany('Anorm\Test\PostModel', 'posts', 'user_id', 'id');

        $result = $rel->getOption('nonexistent_key', 'fallback_value');

        $this->assertEquals('fallback_value', $result);
    }

    public function testGetOptionReturnsNullDefaultForMissingKey()
    {
        $rel = new OneHasMany('Anorm\Test\PostModel', 'posts', 'user_id', 'id');

        $result = $rel->getOption('nonexistent_key');

        $this->assertNull($result);
    }

    public function testGetOptionReturnsConstraintsArray()
    {
        $constraints = ['on_delete' => 'CASCADE', 'on_update' => 'SET NULL'];
        $rel = new OneHasMany('Anorm\Test\PostModel', 'posts', 'user_id', 'id', ['constraints' => $constraints]);

        $result = $rel->getOption('constraints');

        $this->assertIsArray($result);
        $this->assertEquals('CASCADE', $result['on_delete']);
        $this->assertEquals('SET NULL', $result['on_update']);
    }

    public function testGetConstraintNameWithCustomName()
    {
        $rel = new OneHasMany(
            'Anorm\Test\PostModel',
            'posts',
            'user_id',
            'id',
            ['constraints' => ['constraint_name' => 'my_custom_fk', 'on_delete' => 'CASCADE']]
        );

        $name = $rel->getConstraintName('users');

        $this->assertEquals('my_custom_fk', $name);
    }

    public function testGetConstraintNameAutoGeneratedWithoutCustomName()
    {
        $rel = new OneHasMany('Anorm\Test\PostModel', 'posts', 'user_id', 'id');

        // Auto-generate returns fk_{firstArg}_{foreignKey}; first arg is treated as sourceTable
        $name = $rel->getConstraintName('posts');

        $this->assertEquals('fk_posts_user_id', $name);
    }

    public function testGetConstraintNameAutoGeneratedWithTargetTable()
    {
        $rel = new OneHasMany('Anorm\Test\PostModel', 'posts', 'user_id', 'id');

        // generateForeignKeyConstraints calls getConstraintName($targetTable, $sourceTable)
        // so first arg is 'posts' (the related table), and auto-generate returns fk_posts_user_id
        $name = $rel->getConstraintName('posts', 'users');

        $this->assertEquals('fk_posts_user_id', $name);
    }

    public function testGetConstraintNameWithExplicitTargetTable()
    {
        $rel = new OneHasMany('Anorm\Test\CommentModel', 'comments', 'post_id', 'id');

        $name = $rel->getConstraintName('posts', 'comments');

        $this->assertEquals('fk_posts_post_id', $name);
    }

    // -------------------------------------------------------------------------
    // OneHasMany::generateForeignKeyConstraints
    // -------------------------------------------------------------------------

    public function testGenerateForeignKeyConstraintsReturnsArray()
    {
        $rel = new OneHasMany('Anorm\Test\PostModel', 'posts', 'user_id', 'id');

        $constraints = $rel->generateForeignKeyConstraints('users');

        $this->assertIsArray($constraints);
        $this->assertCount(1, $constraints);
    }

    public function testGenerateForeignKeyConstraintsContainsAlterTableSql()
    {
        $rel = new OneHasMany('Anorm\Test\PostModel', 'posts', 'user_id', 'id');

        $constraints = $rel->generateForeignKeyConstraints('users');
        $sql = $constraints[0];

        $this->assertStringContainsString('ALTER TABLE', $sql);
        $this->assertStringContainsString('ADD CONSTRAINT', $sql);
        $this->assertStringContainsString('FOREIGN KEY', $sql);
        $this->assertStringContainsString('REFERENCES', $sql);
    }

    public function testGenerateForeignKeyConstraintsReferencesSourceTable()
    {
        $rel = new OneHasMany('Anorm\Test\PostModel', 'posts', 'user_id', 'id');

        $constraints = $rel->generateForeignKeyConstraints('users');
        $sql = $constraints[0];

        $this->assertStringContainsString('`posts`', $sql);
        $this->assertStringContainsString('`users`', $sql);
        $this->assertStringContainsString('`user_id`', $sql);
        $this->assertStringContainsString('`id`', $sql);
    }

    public function testGenerateForeignKeyConstraintsIncludesOnDeleteAndOnUpdate()
    {
        $rel = new OneHasMany('Anorm\Test\PostModel', 'posts', 'user_id', 'id');

        $constraints = $rel->generateForeignKeyConstraints('users');
        $sql = $constraints[0];

        $this->assertStringContainsString('ON DELETE RESTRICT', $sql);
        $this->assertStringContainsString('ON UPDATE CASCADE', $sql);
    }

    public function testGenerateForeignKeyConstraintsWithCascadeOptions()
    {
        $rel = new OneHasMany(
            'Anorm\Test\PostModel',
            'posts',
            'user_id',
            'id',
            ['constraints' => ['on_delete' => 'CASCADE', 'on_update' => 'SET NULL']]
        );

        $constraints = $rel->generateForeignKeyConstraints('users');
        $sql = $constraints[0];

        $this->assertStringContainsString('ON DELETE CASCADE', $sql);
        $this->assertStringContainsString('ON UPDATE SET NULL', $sql);
    }

    public function testGenerateForeignKeyConstraintsWithCustomConstraintName()
    {
        $rel = new OneHasMany(
            'Anorm\Test\PostModel',
            'posts',
            'user_id',
            'id',
            ['constraints' => ['constraint_name' => 'fk_custom_name']]
        );

        $constraints = $rel->generateForeignKeyConstraints('users');
        $sql = $constraints[0];

        $this->assertStringContainsString('`fk_custom_name`', $sql);
    }

    // -------------------------------------------------------------------------
    // OneHasMany::batchLoad — strategy branches
    // -------------------------------------------------------------------------

    public function testBatchLoadJoinWithSelectionStrategy()
    {
        // Get users and ensure we have > 10 models so the selector can choose JOIN strategy
        // We need fieldSelection and > 10 models to potentially trigger JOIN strategy.
        // Use a custom strategy selector that forces JOIN_WITH_SELECTION.
        $users = DataMapper::find(UserModel::class, $this->pdo)->some();
        $userArray = iterator_to_array($users);

        if (count($userArray) === 0) {
            $this->markTestSkipped('No test data available');
        }

        $user = $userArray[0];
        $relationshipManager = $user->getRelationshipManager();
        $relationship = $relationshipManager->getRelationship('posts');

        if (!($relationship instanceof OneHasMany)) {
            $this->markTestSkipped('Posts relationship not found or not OneHasMany');
        }

        // Create a subclass that overrides getCardinality and estimateDataSize to force JOIN strategy.
        // The JOIN strategy is selected when:
        //   - sourceCount > individual_loading_threshold (10)
        //   - fieldSelection is non-empty
        //   - joinSize < inClauseSize * (1 - join_strategy_threshold(0.5))
        // We duplicate models to exceed the threshold and provide field selection.
        $manyUsers = [];
        for ($i = 0; $i < 20; $i++) {
            $manyUsers[] = $userArray[0];
        }

        // With 20 models and a field selection that reduces data significantly,
        // the JOIN strategy may be selected.
        // The estimateDataSize for OneHasMany with ['id','title'] uses count(fields)*50 bytes
        // = 2*50 = 100 bytes/record * 5 avg * 20 = 10000 bytes
        // The DataSizeEstimator's estimateJoinDataSize will use a small estimate for 2 fields.
        // If joinSize reduction >= 50%, JOIN strategy is chosen.
        // We use field selection with few fields to maximize reduction ratio.
        $fieldSelection = ['id'];

        $batchResults = $relationship->batchLoad($manyUsers, $this->pdo, $fieldSelection);

        $this->assertIsArray($batchResults);
    }

    public function testBatchLoadIndividualLoadingStrategy()
    {
        // With <= 10 source models and no field selection, strategy is INDIVIDUAL_LOADING
        $users = DataMapper::find(UserModel::class, $this->pdo)->some();
        $userArray = iterator_to_array($users);

        if (count($userArray) === 0) {
            $this->markTestSkipped('No test data available');
        }

        $user = $userArray[0];
        $relationshipManager = $user->getRelationshipManager();
        $relationship = $relationshipManager->getRelationship('posts');

        if (!($relationship instanceof OneHasMany)) {
            $this->markTestSkipped('Posts relationship not found or not OneHasMany');
        }

        // With 1-10 models and no field selection, STRATEGY_INDIVIDUAL_LOADING is selected
        // (individual_loading_threshold = 10, sourceCount <= 10 → INDIVIDUAL_LOADING)
        $smallSet = array_slice($userArray, 0, min(3, count($userArray)));
        $batchResults = $relationship->batchLoad($smallSet, $this->pdo, null);

        $this->assertIsArray($batchResults);
        // Individual loading returns results keyed by primary key value
        foreach ($smallSet as $model) {
            if ($model->id !== null) {
                $this->assertArrayHasKey($model->id, $batchResults);
                $this->assertIsArray($batchResults[$model->id]);
            }
        }
    }

    public function testBatchLoadWithNullSourceValueSkipsModel()
    {
        // Test that load() returns [] when sourceValue is null (line 38)
        $rel = new OneHasMany('Anorm\Test\PostModel', 'posts', 'user_id', 'id');

        // Create a model with no id set (null primary key)
        $user = new UserModel($this->pdo);
        $user->id = null;

        $result = $rel->load($user, $this->pdo);

        $this->assertIsArray($result);
        $this->assertEmpty($result);
    }
}
